### ISSUE TITLE
Jawaban nomor 2

### ISSUE THREAD

**Issue by AaEzha** [farhankisnanda/Test-Coding#1]
Assalamu'alaikum warahmatulllahi wabarakatuh

Iseng saya ikut melihat jawaban yang antum berikan, tetapi saya melihat jawaban nomor 1 dan 2 adalah sama. Tidak ada bedanya.

Mungkin lebih mantap lagi kalau antum upload jawaban nomor 2-nya untuk saya dapat mempelajari darinya. Syukron.

**Comment by farhankisnanda** [comment]
Wa'alaikumsalam warahmatullahi wabarakatuh
Sudah diperbaiki ya mas hehehe.

**Comment by AaEzha** [comment]
alhamdulillah
